version: "3.9"

services:
  easiroster:
    build: .
    container_name: easiroster
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - easiroster-data:/app/data

volumes:
  easiroster-data:
