version: "3.9"

services:
  easiroster:
    build: .
    container_name: easiroster
    restart: unless-stopped
    network_mode: "host"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    volumes:
      - easiroster-data:/app/data

volumes:
  easiroster-data:
